[build]
  command = "npm run build:prod"
  publish = "dist"

[functions]
  directory = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Scheduled function for email queue processing
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

  [plugins.inputs]
    [plugins.inputs.schedule]
      "process-email-queue" = "*/5 * * * *"  # Every 5 minutes