[build]
  command = "npm run build:prod"
  publish = "dist"

[dev]
  functionsPort = 8888
  command = "npm run dev"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/admin/dashboard"
  to = "/.netlify/functions/admin-dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/audit-log/stats"
  to = "/.netlify/functions/admin-audit-log-stats"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/audit-log/export"
  to = "/.netlify/functions/admin-audit-log-export"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/users/:id/role"
  to = "/.netlify/functions/admin-users-role?id=:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/users/:id/permissions"
  to = "/.netlify/functions/admin-users-permissions?id=:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/applications/update-status"
  to = "/.netlify/functions/admin-applications-update-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/applications/verify-payment"
  to = "/.netlify/functions/admin-applications-verify-payment"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics/telemetry"
  to = "/.netlify/functions/analytics-telemetry"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics/predictive-dashboard"
  to = "/.netlify/functions/analytics-predictive-dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/api/applications/:id"
  to = "/.netlify/functions/applications-id?id=:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/notifications/dispatch-channel"
  to = "/.netlify/functions/notifications-dispatch-channel"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

