[build]
  command = "npm run build:prod"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/admin/dashboard"
  to = "/.netlify/functions/admin-dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics/telemetry"
  to = "/.netlify/functions/analytics-telemetry"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics/predictive-dashboard"
  to = "/.netlify/functions/analytics-predictive-dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/api/notifications/dispatch-channel"
  to = "/.netlify/functions/notifications-dispatch-channel"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

